language: python

python:
  - "2.7"
  - "3.4"

install:
  - pip install chainer
  - pip install nose
  - pip install coveralls

script:
  - ls
  - nosetests test/functions -a '!gpu,!local' --with-xunit --with-coverage --cover-erase --cover-package=src.functions --verbose

after_success:
  - coveralls
